---
title: "Elemental map"
author: "Neil"
date: "17 March 2017"
output:
    ]
  html_document: 
  pandoc_args: [
      "+RTS", "-K64m",
      "-RTS"
editor_options: 
  chunk_output_type: console
---

#Setup
code not shown
import data, set hooks for webgl, subset edges and times, remove any 'n' using 'use column, make sure time points are correct
```{r include=FALSE}


rm(list=ls())
# getwd tells us where R is looking
getwd()
#setwd tells R where to look
#setwd('file path')



library(AID)
library(vegan)
library(MASS)
library(corrplot)
library(fields)
library(PMCMRplus)
library(gamm4)
library(GISTools)
library(maps)
library(mapdata)
library(PBSmapping)
library(plyr)
library(raster)
library(rgdal)
library(RColorBrewer)
library(rgeos)
library(rasterVis)
library(rgl)
library(sampling)
library(pROC)
library(flux)

## dat<- read.csv(LOAD THE DATA)

## subset the data to extract Age 0 2014 edge data
ed4.14<- subset(dat, dat$Sample=='Age-0_edge')
head(ed4.14)


```


# Precision vs acc plots

```{r}
acc414<-read.csv('file path for previous accuracy csv')

### maximise theta
theta<- acc414$Acur + rev(acc414$Precis)
which(theta==max(theta), arr.ind=T)
th<- which(theta==max(theta), arr.ind=T)

#head(acc114)
head(acc414)

pdf(file="E:/Otolith_chem_paper/Comms_biology_paper/Figs/Acc_prec.pdf",width=4, height=4)

par(mar=c(4,4,0,0)+0.1)

plot(Acur~ Precis, data=acc414, type='n', xlab='Precision', ylab= 'Accuracy', xaxt='n')
axis(1, at= seq(0,1, by=0.2), labels= c('1.0', '0.8','0.6','0.4','0.2','0.0'))
abline(a=0,b=1, lty=2, lwd=3, col='grey55')
acc414[th,]
mthet<-acc414[th,]

lines(Acur~ Precis, data=acc414, lwd=2, col='black')
points(Acur~Precis, data=acc414, pch=24, bg= 'black', cex=1)
segments(mthet[[2]], mthet[[3]], mthet[[2]], mthet[[2]], col='grey50', lwd=1.5)
segments(-0.1, mthet[[3]], mthet[[2]], mthet[[3]], col='grey50', lwd=1.5)
#lines(Acur~Precis, data=acc114, lwd=2, col='red3')
#points(1-Acur~1-Precis, data=acc414, pch=21, bg='red3')

dev.off()

#legend('bottomright', legend=c("March 2014 baseline model", "October 2014 baseline model"),
 #      col=c("slateblue3", "red3"),lty=c(1,1), pch=c(24, 21), pt.bg=c("slateblue3", "red3"),
 #      bty='n')

### look to see what precision is at 90% acc and 80% acc
#

#414
int<- acc414$Acur[which.min(abs(acc414$Acur - 0.75))]
acc414$Precis[which(acc414$Acur==int, arr.ind=T)]

int<- acc414$Acur[which.min(abs(acc414$Acur - 0.8))]
acc414$Precis[which(acc414$Acur==int, arr.ind=T)]

#90%
int<- acc414$Acur[which.min(abs(acc414$Acur - 0.9))]
acc414$Precis[which(acc414$Acur==int, arr.ind=T)]

flux::auc(acc414$Precis, acc414$Acur)


```


#end
