---
title: "Full area/time pull data together"
output: html_document
editor_options: 
  chunk_output_type: console
---


# Setup
```{r setup}
# Reset R's brain
rm(list=ls())
# getwd tells us where R is looking
getwd()
# setwd tells R where to look
setwd("E:/Otolith_chem_paper/Elemental_maps")
#setwd("/Volumes/PHD/R_script/SDM/full_area_time")
getwd()

############################## libraries #####################################################
library(gamm4)
library(fields)
library(KernSmooth)
library(GISTools)
library(SDMTools)
library(maps)
library(mapdata)
library(maptools)
library(RgoogleMaps)
library(PBSmapping)
library(plyr)
library(raster)
library(rgdal)
library(spatial.tools)
library(RColorBrewer)
library(rgeos)
library(AID)
library(gamclass)
library(cvTools)
library(spatstat)
library(ggplot2)
library(fitdistrplus)
library(caret)


source("sdm_functions.R")
source("E:/Otolith_chem_paper/Elemental_maps/soap_checker/soap_check.R")

####################################### map extents ########################################################

###### FULL EXTENT ___________ -10 to -3, 52 to 60 c(xmin, xmax, ymin, ymax)
###### SCOT EXTENT ___________ -10 to  -4, 52 to 55
###### Chem Full Extent____________ -9 to -3, 52 to 59
###### chem scot extent ___________ -9 to -4, 55 to 59
###extents for later
full.ext<- extent(c(-10, -2, 52, 60))
scot.ext<- extent(c(-10, -4, 55, 60))
chemfull.ext<- extent(c(-9, -3, 52, 59))
chemscot.ext<- extent(c(-9, -4, 55, 59))


################################## coord system to assign ####################################################
WGS84<- '+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0'
#### projection
mrc <- '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs'



################################# basic background maps of land and sea #####################################

#### use shape files generated from 'make_extentshp' code use rgdal to read it in to get projections
#scot<- readOGR(dsn="/Volumes/PHD/R_script/SDM", layer="scot")
base<- readOGR(dsn='F:/R_script/SDM', layer="full")
# base<- readOGR(dsn='/Volumes/PHD/R_script/SDM', layer="full")

plot(base)
base<- crop(base, full.ext)

land<- readOGR(dsn= "F:/R_script/SDM/my_layers_collection", layer ='Britain_Proj_Dist')
#land<- readOGR(dsn= "/Volumes/PHD/R_script/SDM/my_layers_collection", layer ='Britain_Proj_Dist')
land<- spTransform(land, CRS(WGS84))
land<- crop(land, full.ext)


plot(base, col ='cornflowerblue')
plot(land, col='cornsilk', add=T)

###################################
### apply projection to sea area and land from above
landT<- spTransform(land, CRS(mrc))
baseT<- spTransform(base, CRS(mrc))

```

# Element data
```{r}

dat<- read.csv('F:/R_script/Microchemistry/elemental_maps/chem2017_Tidy.csv')


#dat<- subset(dat, dat$use=='y')
summary(dat$Area)
max(dat$Pit_no)
min(dat$Pit_no)
# subset for the time points we want
# and get the edge data
edge<- subset(dat, dat$Reverse_pit_no=='1')
edge<- droplevels(edge)
str(edge)
edge$Mn_0<- as.numeric(as.character(edge$Mn_0))



ed4.14<- subset(edge, edge$sample_time ==4.14)
ed4.14<- droplevels(ed4.14)

table(ed4.14$Haul_id)
sum(as.vector(table(ed4.14$Haul_id)))
table(ed4.14$Sex)
table(ed4.14$use)
ed4.14<- subset(ed4.14, ed4.14$use == 'y')

#make sure we are looking at the correct months


##### 4.14
summary(ed4.14$Sample_months)
summary(ed4.14$pred_month)

## remove ones which are way too early
#try with out this look at element spread in graphs
#ed4.14<- subset(ed4.14, ed4.14$pred_month != 'Aug' & ed4.14$pred_month != 'Jul')


summary(ed4.14$pred_month)
ed4.14<- droplevels(ed4.14)

# Go through each element in turn, check for normality
# 
#Na
# 
# hist(ed4.14$Na)
# shapiro.test(ed4.14$Na)  ##Normal
# qqnorm(ed4.14$Na); qqline(ed4.14$Na, col = 2)

# 
# # growth relationship
# plot(Na~Dist_to_pit, data=ed4.14)
# lineNa<- lm(Na~Dist_to_pit, data=ed4.14) ##  not-Sig
# summary(lineNa)
# abline(lineNa)


chem<- data.frame('ID'= ed4.14$ID, 'Na'=ed4.14$Na)

# 
# #Mg
# hist(ed4.14$Mg)
# shapiro.test(ed4.14$Mg)  ##Normal
# qqnorm(ed4.14$Mg); qqline(ed4.14$Mg, col = 2)
# 
# # 
# plot(Mg~Dist_to_pit, data=ed4.14)
# lineMg<- lm(Mg~Dist_to_pit, data=ed4.14) ## non-Sig
# summary(lineMg)
# abline(lineMg)

chem<- cbind(chem, 'Mg'=ed4.14$Mg)

# 
# #P
# hist(ed4.14$P)
# shapiro.test(ed4.14$P)  ##Normal
# qqnorm(ed4.14$P); qqline(ed4.14$P, col = 2)

# 
# 
# plot(P~Dist_to_pit, data=ed4.14)
# lineP<- lm(P~Dist_to_pit, data=ed4.14) ## Non - Sig
# summary(lineP)

chem<- cbind(chem, 'P'=ed4.14$P)
# 
# #Ba
# summary(ed4.14$Ba)
# hist(ed4.14$Ba)
# shapiro.test(ed4.14$Ba)  ##Non-Normal
# qqnorm(ed4.14$Ba); qqline(ed4.14$Ba, col = 2)
# 
# #what distrobution
# hist(ed4.14$Ba)
# descdist(ed4.14$Ba, boot=500)
# f<-fitdistr(ed4.14$Ba, 'gamma')
# plotdist(ed4.14$Ba, distr='gamma', para=list(shape=1.6, rate=0.5))
# rate.est<- mean(ed4.14$Ba)/var(ed4.14$Ba)
# rate.est
# shape.est<- (mean(ed4.14$Ba)^2)/var(ed4.14$Ba)
# shape.est
# plotdist(ed4.14$Ba, distr='gamma', para=list(shape=shape.est, rate=rate.est))

chem<- cbind(chem, 'Ba'=ed4.14$Ba)


#Sr
# 
# hist(ed4.14$Sr)
# shapiro.test(ed4.14$Sr)  ##Normal
# qqnorm(ed4.14$Sr); qqline(ed4.14$Sr, col = 2)

# 
# 
# plot(Sr~Dist_to_pit, data=ed4.14)
# lineSr<- lm(Sr~Dist_to_pit, data=ed4.14) ## not Sig
# summary(lineSr)
# abline(lineSr)


chem<- cbind(chem, 'Sr'=ed4.14$Sr)

#Mn 0
# summary(ed4.14$Mn)
# 
# hist(ed4.14$Mn_0)
# shapiro.test(ed4.14$Mn_0)  ##Non-Normal
# qqnorm(ed4.14$Mn_0); qqline(ed4.14$Mn_0, col = 2)
# 
# #what distrobution
# hist(ed4.14$Mn_0+0.1)
# descdist(ed4.14$Mn_0+0.1, boot=500)
# f<-fitdistr(ed4.14$Mn_0+0.1, 'gamma')
# plotdist(ed4.14$Mn_0+0.1, distr='gamma', para=list(shape=1.5, rate=0.6))
# rate.est<- mean(ed4.14$Mn_0+0.1)/var(ed4.14$Mn_0+0.1)
# rate.est
# shape.est<- (mean(ed4.14$Mn_0+0.1)^2)/var(ed4.14$Mn_0+0.1)
# shape.est
# plotdist(ed4.14$Mn_0+0.1, distr='gamma', para=list(shape=shape.est, rate=rate.est))

chem<- cbind(chem, 'Mn'=ed4.14$Mn_0+0.1)


#Zn 
# summary(ed4.14$Zn)
# 
# hist(ed4.14$Zn)
# shapiro.test(ed4.14$Zn)  ##Non-Normal
# qqnorm(ed4.14$Zn); qqline(ed4.14$Zn, col = 2)
# 
# #normalise
# Znout<- boxcoxnc(ed4.14$Zn)
# ZnT<-Znout$tf.data
# shapiro.test(ZnT)
# qqnorm(ZnT); qqline(ZnT, col = 2)   ##not Normal
# hist(ZnT)
# 
# # 
# # plot(Zn~Dist_to_pit, data=ed4.14)
# # lineZn<- lm(Zn~Dist_to_pit, data=ed4.14) ## not Sig
# # summary(lineZn)
# # abline(lineZn)


chem<- cbind(chem, 'Zn'=ed4.14$Zn)

#((0.032424^-0.38)-1)/-0.38# box cox transformation used on measurement error


#Ni
# summary(ed4.14$Ni)
# 
# hist(ed4.14$Ni)
# shapiro.test(ed4.14$Ni)  ##Non-Normal
# qqnorm(ed4.14$Ni); qqline(ed4.14$Ni, col = 2)
# 
# #normalise
# Niout<- boxcoxnc(ed4.14$Ni)
# NiT<-Niout$tf.data
# shapiro.test(NiT)
# qqnorm(NiT); qqline(NiT, col = 2)   ## not - Normal
# hist(NiT)

# 
# plot(Ni~Dist_to_pit, data=ed4.14)
# lineNi<- lm(Ni~Dist_to_pit, data=ed4.14) ## Sig
# summary(lineNi)
# abline(lineNi)
# 
# # corect for length
# 
# NiCor<- lineNi$residuals
# 
# hist(NiCor)
# shapiro.test(NiCor)  ##not Normal
# qqnorm(NiCor); qqline(NiCor, col = 2)


chem<- cbind(chem, 'Ni'=ed4.14$Ni)

#Cu
# summary(ed4.14$Cu)
# 
# hist(ed4.14$Cu)
# shapiro.test(ed4.14$Cu)  ##Non-Normal
# qqnorm(ed4.14$Cu); qqline(ed4.14$Cu, col = 2)
# 
# #normalise
# Cuout<- boxcoxnc(ed4.14$Cu) 
# CuT<-Cuout$tf.data
# shapiro.test(CuT)
# qqnorm(CuT); qqline(CuT, col = 2)   ## Normal
# hist(CuT)
# 
# # 
# # plot(CuT~Dist_to_pit, data=ed4.14)
# # lineCuT<- lm(CuT~Dist_to_pit, data=ed4.14) ## non Sig
# # summary(lineCuT)
# # abline(lineCuT)
# 
# 

chem<- cbind(chem, 'Cu'=CuT)






#Rb
# summary(ed4.14$Rb)
# 
# hist(ed4.14$Rb)
# shapiro.test(ed4.14$Rb)  ##Non-Normal
# qqnorm(ed4.14$Rb); qqline(ed4.14$Rb, col = 2)
# 
# #normalise
# Rbout<- boxcoxnc(ed4.14$Rb)
# RbT<-Rbout$tf.data
# shapiro.test(RbT)
# qqnorm(RbT); qqline(RbT, col = 2)   ##not- Normal
# hist(RbT)
# 
# 
# plot(Rb~Dist_to_pit, data=ed4.14)
# lineRb<- lm(Rb~Dist_to_pit, data=ed4.14) ## non Sig
# summary(lineRb)
# abline(lineRb)

#what distrobution
# hist(ed4.14$Rb)
# descdist(ed4.14$Rb, boot=500)
# f<-fitdistr(ed4.14$Rb, 'gamma')
# plotdist(ed4.14$Rb, distr='gamma', para=list(shape=4.5, rate=70.7))
# rate.est<- mean(ed4.14$Rb)/var(ed4.14$Rb)
# rate.est
# shape.est<- (mean(ed4.14$Rb)^2)/var(ed4.14$Rb)
# shape.est
# plotdist(ed4.14$Rb, distr='gamma', para=list(shape=shape.est, rate=rate.est))
chem<- cbind(chem, 'Rb'=ed4.14$Rb)

 
#Cr_0
# summary(ed4.14$Cr)
# 
# hist(ed4.14$Cr)
# shapiro.test(ed4.14$Cr)  ##Non-Normal
# qqnorm(ed4.14$Cr); qqline(ed4.14$Cr, col = 2)
# 
# #normalise
# Crout<- boxcoxnc(ed4.14$Cr)   ##non Normal

# 
# 
# plot(Cr~Dist_to_pit, data=ed4.14)
# lineCr<- lm(Cr~Dist_to_pit, data=ed4.14) ## non Sig
# summary(lineCr)
# abline(lineCr)


chem<- cbind(chem, 'Cr'=ed4.14$Cr)

#Li
# summary(ed4.14$Li)
# 
# hist(ed4.14$Li+1)
# shapiro.test(ed4.14$Li)  ##Non-Normal
# qqnorm(ed4.14$Li); qqline(ed4.14$Li, col = 2)
# 
# #normalise
# Liout<- boxcoxnc(ed4.14$Li)   ##non Normal
# 
# # 
# # 
# # plot(Li~Dist_to_pit, data=ed4.14)
# # lineLi<- lm(Li~Dist_to_pit, data=ed4.14) ## non -Sig
# # summary(lineLi)
# # abline(lineLi)
# 
# #what distrobution
# hist(ed4.14$Li)
# descdist(ed4.14$Li+1, boot=500)
# f<-fitdistr(ed4.14$Li+1, 'gamma')
# f
# plotdist(ed4.14$Li+1, distr='gamma', para=list(shape=29.27, rate=21.53))
# 
# rate.est<- mean(ed4.14$Li+1)/var(ed4.14$Li+1)
# rate.est
# shape.est<- (mean(ed4.14$Li+1)^2)/var(ed4.14$Li+1)
# shape.est
# plotdist(ed4.14$Li+1, distr='gamma', para=list(shape=shape.est, rate=rate.est))

chem<- cbind(chem, 'Li'=ed4.14$Li+1)

# 
# #Al &0
# summary(ed4.14$Al)
# 
# hist(ed4.14$Al_0)
# shapiro.test(ed4.14$Al_0)  ##Non-Normal
# qqnorm(ed4.14$Al_0); qqline(ed4.14$Al_0, col = 2)
# 
# #normalise
# Alout<- boxcoxnc(ed4.14$Al_0+1) ## non Normal
# 
# # 
# # plot(Al_0~Dist_to_pit, data=ed4.14)
# # lineAl<- lm(Al_0~Dist_to_pit, data=ed4.14) ## Sig
# # summary(lineAl)
# # abline(lineAl)


chem<- cbind(chem, 'Al'=ed4.14$Al_0)
# 
# 
# #Sc &0
# summary(ed4.14$Sc)
# 
# 
# hist(ed4.14$Sc_0+1)
# shapiro.test(ed4.14$Sc_0)  ##Non-Normal
# qqnorm(ed4.14$Sc_0); qqline(ed4.14$Sc_0, col = 2)
# 
# #normalise
Scout<- boxcoxnc(ed4.14$Sc_0+1)   ## non Normal

# 
# plot(Sc_0~Dist_to_pit, data=ed4.14)
# lineSc<- lm(Sc_0~Dist_to_pit, data=ed4.14) ## not Sig
# summary(lineSc)
# abline(lineSc)
# 
# #what distrobution
# hist(exp(ed4.14$Sc_0))
# hist(ed4.14$Sc_0+1)
# #ed4.14$Sc_0<- exp(ed4.14$Sc_0)
# 
# descdist(ed4.14$Sc_0+1, boot=500)
# f<-fitdistr(ed4.14$Sc_0+1, 'gamma')
# f
# plotdist(ed4.14$Sc_0+1, distr='gamma', para=list(shape=3935, rate= 3861))
# 
# rate.est<- mean(ed4.14$Sc_0+1)/var(ed4.14$Sc_0+1)
# rate.est
# shape.est<- (mean(ed4.14$Sc_0+1)^2)/var(ed4.14$Sc_0+1)
# shape.est
# #plotdist(exp(ed4.14$Sc_0), distr='gamma', demp=T, para=list(shape=shape.est, rate=rate.est))
# 
# plotdist(ed4.14$Sc_0+1, distr='gamma', demp=F, para=list(shape=shape.est, rate=rate.est))
# 

# chem<- cbind(chem, 'Sc'=ed4.14$Sc_0+1)
# 
# #Ti &0
# summary(ed4.14$Ti)
# 
# hist(ed4.14$Ti_0)
# shapiro.test(ed4.14$Ti_0)  ##Non-Normal
# qqnorm(ed4.14$Ti_0); qqline(ed4.14$Ti_0, col = 2)
# 
# #normalise
# Tiout<- boxcoxnc(ed4.14$Ti_0+1)##non Normal
# 
# # 
# # plot(Ti~Dist_to_pit, data=ed4.14)
# # lineTi<- lm(Ti~Dist_to_pit, data=ed4.14) ## non Sig
# # summary(lineTi)
# # abline(lineTi)


chem<- cbind(chem, 'Ti'=ed4.14$Ti_0)
# 
# #Y &0
# summary(ed4.14$Y)
# 
# 
# hist(ed4.14$Y_0)
# shapiro.test(ed4.14$Y_0)  ##Non-Normal
# qqnorm(ed4.14$Y_0); qqline(ed4.14$Y_0, col = 2)
# 
# #normalise
# Yout<- boxcoxnc(ed4.14$Y_0+1) ## non Normal
# # 
# # plot(Y_0~Dist_to_pit, data=ed4.14)
# # lineY<- lm(Y_0~Dist_to_pit, data=ed4.14) ## non Sig
# # summary(lineY)
# # abline(lineY)
# 

chem<- cbind(chem, 'Y'=ed4.14$Y_0)
# 
# #Pb &0
# summary(ed4.14$Pb)
# 
# hist(ed4.14$Pb_0)
# shapiro.test(ed4.14$Pb_0)  ##Non-Normal
# qqnorm(ed4.14$Pb_0); qqline(ed4.14$Pb_0, col = 2)

#normalise
# Pbout<- boxcoxnc(ed4.14$Pb_0+1) ## non Normal
# 
# # 
# # plot(Pb_0~Dist_to_pit, data=ed4.14)
# # linePb<- lm(Pb_0~Dist_to_pit, data=ed4.14) ## Sig
# # summary(linePb)
# # abline(linePb)


chem<- cbind(chem, 'Pb'=ed4.14$Pb_0)

head(chem)
summary(chem)
str(chem)
names(ed4.14)

# remove the outlier from previously
chem<- chem[-57,]
ed4.14<- ed4.14[-57,]

# bind some other useful stuff
chem<- cbind(chem, 'Area'= ed4.14$Area, 'Haul_id'= as.numeric(as.factor(ed4.14$Haul_id)), 'radius' = ed4.14$Dist_to_pit, 'long'= ed4.14$Mid_long, 'lat'= ed4.14$Mid_lat, 'HaulF'= as.factor(ed4.14$Haul_id))

```



# make elements sp object
```{r}

coords.tmp<- cbind(chem$long, chem$lat)
## create spdf object
chem.spdf<- SpatialPointsDataFrame(coords.tmp, data = data.frame(chem),
                                   proj4string = CRS(WGS84))

#### trim biological layers to fit extent
chem.spdfT<- crop(chem.spdf, full.ext)
chem.spdfT<- spTransform(chem.spdfT, CRS(mrc))


###plot to see abundances

### 
plot(baseT)
choropleth(chem.spdfT, chem$Na, pch=19, cex = 1.4, main = 'non-transformed data', add=T)
plot(chem.spdfT, pch=1, add=T, cex=1.4)

table(chem$Haul_id)
sum(as.vector(table(chem$Haul_id)))



```


#Read in environmental data layers
```{r}
# 
# #temp
# temp.r1.14<- raster('F:/R_script/Microchemistry/Elemental_maps/Env_layers/temp1_14.grd')
# temp.r4.14<- raster('F:/R_script/Microchemistry/Elemental_maps/Env_layers/temp4_14.grd')
# temp.r1.15<- raster('F:/R_script/Microchemistry/Elemental_maps/Env_layers/temp1_15.grd')
# 
# plot(temp.r1.14)
# plot(temp.r4.14)
# plot(temp.r1.15)
# 
# 
# #sal
# sal.r1.14<- raster('F:/R_script/Microchemistry/Elemental_maps/Env_layers/sal1_14.grd')
# sal.r4.14<- raster('F:/R_script/Microchemistry/Elemental_maps/Env_layers/sal4_14.grd')
# sal.r1.15<- raster('F:/R_script/Microchemistry/Elemental_maps/Env_layers/sal1_15.grd')
# 
# plot(sal.r1.14)
# plot(sal.r4.14)
# plot(sal.r1.15)
# 
# #sed
# sed.r<- raster('F:/R_script/Microchemistry/Elemental_maps/Env_layers/sed.grd')
# as.factor(sed.r)
# plot(sed.r)
# 
# #
# chl.r1.14<- raster('F:/R_script/Microchemistry/Elemental_maps/Env_layers/chl1_14.grd')
# chl.r4.14<- raster('F:/R_script/Microchemistry/Elemental_maps/Env_layers/chl4_14.grd')
# chl.r1.15<- raster('F:/R_script/Microchemistry/Elemental_maps/Env_layers/chl1_15.grd')
# 
# plot(chl.r1.14)
# plot(chl.r4.14)
# plot(chl.r1.15)
# 
# #dist
# alldist.r<- raster('F:/R_script/Microchemistry/Elemental_maps/Env_layers/alldist.grd')
# 
# plot(alldist.r)
# 
# #aspect
# aspect.r<- raster('F:/R_script/Microchemistry/Elemental_maps/Env_layers/aspect.grd')
# 
# plot(aspect.r)
# 
# #bath
# bath.r<- raster('F:/R_script/Microchemistry/Elemental_maps/Env_layers/bath.grd')
# 
# plot(bath.r)
# 


```





# Plot data and layers
```{r}

#bath
bath.r<- raster('F:/R_script/Microchemistry/Elemental_maps/Env_layers/bath.grd')

plot(bath.r)
################################# basic background maps of land and sea #####################################

#### use shape files generated from 'make_extentshp' code use rgdal to read it in to get projections
#scot<- readOGR(dsn="/Volumes/PHD/R_script/SDM", layer="scot")
base<- readOGR(dsn='F:/R_script/SDM', layer="full")
# base<- readOGR(dsn='/Volumes/PHD/R_script/SDM', layer="full")

plot(base)
base<- crop(base, full.ext)

land<- readOGR(dsn= "F:/R_script/SDM/my_layers_collection", layer ='Britain_Proj_Dist')
#land<- readOGR(dsn= "/Volumes/PHD/R_script/SDM/my_layers_collection", layer ='Britain_Proj_Dist')
land<- spTransform(land, CRS(WGS84))
land<- crop(land, full.ext)


plot(base, col ='cornflowerblue')
plot(land, col='cornsilk', add=T)

###################################
### apply projection to sea area and land from above
landT<- spTransform(land, CRS(mrc))
baseT<- spTransform(base, CRS(mrc))

#read in data layers for speed
pNa<- raster('F:/R_script/Microchemistry/elemental_maps/elem_layers/modelNa_414.grd')
eNa<- raster('F:/R_script/Microchemistry/elemental_maps/elem_layers/er_modelNa_414')
pMg<- raster('F:/R_script/Microchemistry/elemental_maps/elem_layers/modelMg_414.grd')
eMg<- raster('F:/R_script/Microchemistry/elemental_maps/elem_layers/er_modelMg_414')
pP<- raster('F:/R_script/Microchemistry/elemental_maps/elem_layers/modelP_414.grd')
eP<- raster('F:/R_script/Microchemistry/elemental_maps/elem_layers/er_modelP_414')
pBa<- raster('F:/R_script/Microchemistry/elemental_maps/elem_layers/modelBa_414.grd')
eBa<- raster('F:/R_script/Microchemistry/elemental_maps/elem_layers/er_modelBa_414')
pSr<- raster('F:/R_script/Microchemistry/elemental_maps/elem_layers/modelSr_414.grd')
eSr<- raster('F:/R_script/Microchemistry/elemental_maps/elem_layers/er_modelSr_414')
pMn<- raster('F:/R_script/Microchemistry/elemental_maps/elem_layers/modelMn_414.grd')
eMn<- raster('F:/R_script/Microchemistry/elemental_maps/elem_layers/er_modelMn_414')
pZn<- raster('F:/R_script/Microchemistry/elemental_maps/elem_layers/modelZn_414.grd')
eZn<- raster('F:/R_script/Microchemistry/elemental_maps/elem_layers/er_modelZn_414')
pRb<- raster('F:/R_script/Microchemistry/elemental_maps/elem_layers/modelRb_414.grd')
eRb<- raster('F:/R_script/Microchemistry/elemental_maps/elem_layers/er_modelRb_414')
pLi<- raster('F:/R_script/Microchemistry/elemental_maps/elem_layers/modelLi_414.grd')
eLi<- raster('F:/R_script/Microchemistry/elemental_maps/elem_layers/er_modelLi_414')



##Temp cols
display.brewer.all()

area.shades<- brewer.pal(9,'Set1')
#spec<- brewer.pal(11,'Spectral')
spec<-colorRampPalette(rev(brewer.pal(11,'Spectral')))
dave.heat<- colorRampPalette(rev(brewer.pal(9,'Blues')[4:9]))
temp.col<- colorRampPalette(rev(c(brewer.pal(9, 'YlOrRd'), brewer.pal(9, 'RdPu')[7:9])))


######## plot environmental data
L <- parse(text = paste(c(8,6,4), "*degree ~W", sep = "")) # longitudes
LN<- parse(text = paste(c(52:60), "*degree ~N", sep = "")) #lats

# extract coords for the tick marks
longs<- c(-2.5,-4,-6,-8,-10 )
lats<- c(54.5, 54.5, 54.5, 54.5, 54.5)
S <- SpatialPoints(cbind(longs,lats), CRS(WGS84))

ST<- spTransform(S, CRS(mrc))
plot(ST)
coordinates(ST)

longs<- c(-6.5,-6.5,-6.5,-6.5,-6.5, -6.5, -6.5, -6.5, -6.5 )
lats<- c(52, 53, 54, 55, 56, 57, 58, 59, 60)
S <- SpatialPoints(cbind(longs,lats), CRS(WGS84))

ST<- spTransform(S, CRS(mrc))
plot(ST)
coordinates(ST)

##get sizes of all cells in raster [km2]
cell_size <-raster::area(pSr, na.rm=TRUE, weights=FALSE)

#delete NAs from vector of all raster cells
##NAs lie outside of the rastered region, can thus be omitted
cell_size<-cell_size[!is.na(cell_size)]
#compute area [km2] of all cells in geo_raster
raster_area<-length(cell_size)*median(cell_size)

```

##plot Sr
```{r}
#Sr

gr.bl<- colorRampPalette(brewer.pal(9,'GnBu'), bias=0.6)


pdf(file="E:/Otolith_chem_paper/Comms_biology_paper/Figs/Sr_pred.pdf",width=7.2, height=11.6)

par(mar=c(0,0,0,0)+0.1)


image(pNa, col = 'white', xaxt='n', yaxt='n',xlim=c(-1057535.2,-278298.7), ylim= c(6800125,8399738), xlab=NA, ylab=NA) ###use image to keep plot in same 'window' for plotting - plot() extends plotting area
image(pSr, col = gr.bl(1000), zlim= c(minValue(eSr),maxValue(pSr)), add=T)
plot(landT, add =T, col = 'grey70')
plot(chem.spdfT, add=T, pch=19, col='black', cex=4)

dev.off()

#axis(1, at=c( -890555.9, -667916.9, -445278.0), L, lwd.ticks=1, cex.axis=2, padj=0.8)
#abline(h=-1057535.2)
#axis(2, at=c(6800125, 6982998, 7170156, 7361866, 7558416, 7760119, 7967318, 8180387, 8399738), labels=LN, lwd.ticks=1, pos=-1057535.2, las=1,cex.axis=2)
#axis(4, at=c(6800125,8399738), labels=NA, lwd.ticks=0, pos=-278298.7)
#axis(3, at=c(-1066000,-333000), labels=NA, lwd.ticks=0, pos=8404000)
gr.bl<- colorRampPalette(brewer.pal(9,'GnBu'), bias=1)


pdf(file="E:/Otolith_chem_paper/Comms_biology_paper/Figs/Sr_leg.pdf",width=7.2, height=11.6)

par(mar=c(0,0,0,0)+0.1)

image(pNa, col = 'white', xaxt='n', yaxt='n',xlim=c(-1057535.2,-278298.7), ylim= c(6800125,8399738), xlab=NA, ylab=NA) 

#Legend
plot(pSr, horizontal=F, zlim= c(minValue(eSr),maxValue(pSr)),  smallplot= c(0.6, 0.62, 0.2, 0.8), col = gr.bl(1000),legend.only=TRUE,  axis.args = list(cex.axis = 2))

dev.off()

gr.bl<- colorRampPalette(brewer.pal(9,'GnBu'), bias=1.3)


pdf(file="E:/Otolith_chem_paper/Comms_biology_paper/Figs/Sr_err.pdf",width=7.2, height=11.6)

par(mar=c(0,0,0,0)+0.1)

#Sr- er
#par(mfrow=c(2,2))
#par(mar = c(5,6,4,2))
image(pNa, col = 'white', xaxt='n', yaxt='n',xlim=c(-1057535.2,-278298.7), ylim= c(6800125,8399738), xlab=NA, ylab=NA) ###use image to keep plot in same 'window' for plotting - plot() extends plotting area
image(eSr, col = gr.bl(1000), zlim= c(minValue(eSr),maxValue(pSr)), add=T)
plot(landT, add =T, col = 'grey70')
plot(chem.spdfT, add=T, pch=19, col='black', cex=4)

dev.off()


# axis(1, at=c( -890555.9, -667916.9, -445278.0), L, lwd.ticks=1, cex.axis=2, padj=0.8)
# abline(h=-1057535.2)
# axis(2, at=c(6800125, 6982998, 7170156, 7361866, 7558416, 7760119, 7967318, 8180387, 8399738), labels=LN, lwd.ticks=1, pos=-1057535.2, las=1,cex.axis=2)
# axis(4, at=c(6800125,8399738), labels=NA, lwd.ticks=0, pos=-278298.7)
#axis(3, at=c(-1066000,-333000), labels=NA, lwd.ticks=0, pos=8404000)

# pdf(file="E:/Otolith_chem_paper/Comms_biology_paper/Figs/Sr_err_leg.pdf",width=7.2, height=11.6)
# 
# par(mar=c(0,0,0,0)+0.1)
# 
# image(pNa, col = 'white', xaxt='n', yaxt='n',xlim=c(-1057535.2,-278298.7), ylim= c(6800125,8399738), xlab=NA, ylab=NA) 
# 
# #Legend
# plot(scale(eSr, center=F, scale=F), horizontal=T,  smallplot= c(0.2, 0.8, 0.6, 0.62),  col = gr.bl(1000),legend.only=TRUE,  axis.args = list(cex.axis = 2))
# 
# dev.off()

```

##Plot Mn
```{r}

gr.bl<- colorRampPalette(brewer.pal(9,'GnBu'), bias=1.5)



pdf(file="E:/Otolith_chem_paper/Comms_biology_paper/Figs/Mn_pred.pdf",width=7.2, height=11.6)

par(mar=c(0,0,0,0)+0.1)
#par(mfrow=c(2,2))
image(pNa, col = 'white', xaxt='n', yaxt='n',xlim=c(-1057535.2,-278298.7), ylim= c(6800125,8399738), xlab=NA, ylab=NA) ###use image to keep plot in same 'window' for plotting - plot() extends plotting area
image(pMn, col = gr.bl(1000), zlim= c(minValue(eMn),maxValue(eMn)), add=T)
plot(landT, add =T, col = 'grey70')
plot(chem.spdfT, add=T, pch=19, col='black', cex=4)

dev.off()


# axis(1, at=c( -890555.9, -667916.9, -445278.0), L, lwd.ticks=1, cex.axis=2, padj=0.8)
# abline(h=-1057535.2)
# axis(2, at=c(6800125, 6982998, 7170156, 7361866, 7558416, 7760119, 7967318, 8180387, 8399738), labels=LN, lwd.ticks=1, pos=-1057535.2, las=1,cex.axis=2)
# axis(4, at=c(6800125,8399738), labels=NA, lwd.ticks=0, pos=-278298.7)
#axis(3, at=c(-1066000,-333000), labels=NA, lwd.ticks=0, pos=8404000)

gr.bl<- colorRampPalette(brewer.pal(9,'GnBu'), bias=1)


pdf(file="E:/Otolith_chem_paper/Comms_biology_paper/Figs/Mn_leg.pdf",width=7.2, height=11.6)

par(mar=c(0,0,0,0)+0.1)

image(pNa, col = 'white', xaxt='n', yaxt='n',xlim=c(-1057535.2,-278298.7), ylim= c(6800125,8399738), xlab=NA, ylab=NA)
#Legend
plot(pMn, horizontal=F,  zlim= c(minValue(eMn),maxValue(eMn)), smallplot= c( 0.6, 0.62, 0.2, 0.8),  col = gr.bl(1000),legend.only=TRUE,  axis.args = list(cex.axis = 2))


dev.off()

gr.bl<- colorRampPalette(brewer.pal(9,'GnBu'), bias=0.6)


pdf(file="E:/Otolith_chem_paper/Comms_biology_paper/Figs/Mn_err.pdf",width=7.2, height=11.6)

par(mar=c(0,0,0,0)+0.1)

#Mn- er
#par(mfrow=c(2,2))
image(pNa, col = 'white', xaxt='n', yaxt='n',xlim=c(-1057535.2,-278298.7), ylim= c(6800125,8399738), xlab=NA, ylab=NA) ###use image to keep plot in same 'window' for plotting - plot() extends plotting area
image(eMn, col = gr.bl(1000), zlim= c(minValue(eMn),maxValue(eMn)), add=T)
plot(landT, add =T, col = 'grey70')
plot(chem.spdfT, add=T, pch=19, col='black', cex=4)
# 
# axis(1, at=c( -890555.9, -667916.9, -445278.0), L, lwd.ticks=1, cex.axis=2, padj=0.8)
# abline(h=-1057535.2)
# axis(2, at=c(6800125, 6982998, 7170156, 7361866, 7558416, 7760119, 7967318, 8180387, 8399738), labels=LN, lwd.ticks=1, pos=-1057535.2, las=1,cex.axis=2)
# axis(4, at=c(6800125,8399738), labels=NA, lwd.ticks=0, pos=-278298.7)
#axis(3, at=c(-1066000,-333000), labels=NA, lwd.ticks=0, pos=8404000)


dev.off()



# pdf(file="E:/Otolith_chem_paper/Comms_biology_paper/Figs/Mn_err_leg.pdf",width=7.2, height=11.6)
# 
# par(mar=c(0,0,0,0)+0.1)
# 
# image(pNa, col = 'white', xaxt='n', yaxt='n',xlim=c(-1057535.2,-278298.7), ylim= c(6800125,8399738), xlab=NA, ylab=NA)
# #Legend
# plot(scale(eMn, center=T, scale=F), horizontal=T,  smallplot= c(0.2, 0.8, 0.6, 0.62),  col = gr.bl(1000),legend.only=TRUE,  axis.args = list(cex.axis = 2))
# 
# 
# 
# dev.off()


```

##Other elements
```{r}

###Zn


#par(mfrow=c(2,2))
# par(mar = c(5,6,4,2))
# image(pNa, col = 'white', xaxt='n', yaxt='n',xlim=c(-1057535.2,-278298.7), ylim= c(6800125,8399738), xlab=NA, ylab=NA) ###use image to keep plot in same 'window' for plotting - plot() extends plotting area
# image(pZn, col = spec(1000), zlim= c(minValue(pZn),maxValue(pZn)), add=T)
# plot(landT, add =T, col = 'cornsilk3')
# plot(chem.spdfT, add=T, pch=19, col='black', cex=2.5)
# 
# axis(1, at=c( -890555.9, -667916.9, -445278.0), L, lwd.ticks=1, cex.axis=2, padj=0.8)
# abline(h=-1057535.2)
# axis(2, at=c(6800125, 6982998, 7170156, 7361866, 7558416, 7760119, 7967318, 8180387, 8399738), labels=LN, lwd.ticks=1, pos=-1057535.2, las=1,cex.axis=2)
# axis(4, at=c(6800125,8399738), labels=NA, lwd.ticks=0, pos=-278298.7)
# #axis(3, at=c(-1066000,-333000), labels=NA, lwd.ticks=0, pos=8404000)
# 
# #Legend
# plot(round(pZn,3), horizontal=F,  smallplot= c(0.6,0.62,0.2,0.8), col = spec(1000),legend.only=TRUE,  axis.args = list(cex.axis = 2))
# 
# #Cu- er
# #par(mfrow=c(2,2))
# par(mar = c(5,6,4,2))
# image(pNa, col = 'white', xaxt='n', yaxt='n',xlim=c(-1057535.2,-278298.7), ylim= c(6800125,8399738), xlab=NA, ylab=NA) ###use image to keep plot in same 'window' for plotting - plot() extends plotting area
# image(eZn, col = spec(1000), zlim= c(minValue(eZn),maxValue(eZn)), add=T)
# plot(landT, add =T, col = 'cornsilk3')
# plot(chem.spdfT, add=T, pch=19, col='black', cex=2.5)
# 
# axis(1, at=c( -890555.9, -667916.9, -445278.0), L, lwd.ticks=1, cex.axis=2, padj=0.8)
# abline(h=-1057535.2)
# axis(2, at=c(6800125, 6982998, 7170156, 7361866, 7558416, 7760119, 7967318, 8180387, 8399738), labels=LN, lwd.ticks=1, pos=-1057535.2, las=1,cex.axis=2)
# axis(4, at=c(6800125,8399738), labels=NA, lwd.ticks=0, pos=-278298.7)
# #axis(3, at=c(-1066000,-333000), labels=NA, lwd.ticks=0, pos=8404000)
# 
# #Legend
# plot(round(eZn,3), horizontal=F,  smallplot= c(0.6,0.62,0.2,0.8), col = spec(1000),legend.only=TRUE,  axis.args = list(cex.axis = 2))
# 

###Rb

# 
# #par(mfrow=c(2,2))
# par(mar = c(5,6,4,2))
# image(pNa, col = 'white', xaxt='n', yaxt='n',xlim=c(-1057535.2,-278298.7), ylim= c(6800125,8399738), xlab=NA, ylab=NA) ###use image to keep plot in same 'window' for plotting - plot() extends plotting area
# image(pRb, col = spec(1000), zlim= c(minValue(pRb),maxValue(pRb)), add=T)
# plot(landT, add =T, col = 'cornsilk3')
# plot(chem.spdfT, add=T, pch=19, col='black', cex=2.5)
# 
# axis(1, at=c( -890555.9, -667916.9, -445278.0), L, lwd.ticks=1, cex.axis=2, padj=0.8)
# abline(h=-1057535.2)
# axis(2, at=c(6800125, 6982998, 7170156, 7361866, 7558416, 7760119, 7967318, 8180387, 8399738), labels=LN, lwd.ticks=1, pos=-1057535.2, las=1,cex.axis=2)
# axis(4, at=c(6800125,8399738), labels=NA, lwd.ticks=0, pos=-278298.7)
# #axis(3, at=c(-1066000,-333000), labels=NA, lwd.ticks=0, pos=8404000)
# 
# #Legend
# plot(pRb, horizontal=F,  smallplot= c(0.6,0.62,0.2,0.8), col = spec(1000),legend.only=TRUE,  axis.args = list(cex.axis = 2))
# 
# #Rb- er
# #par(mfrow=c(2,2))
# par(mar = c(5,6,4,2))
# image(pNa, col = 'white', xaxt='n', yaxt='n',xlim=c(-1057535.2,-278298.7), ylim= c(6800125,8399738), xlab=NA, ylab=NA) ###use image to keep plot in same 'window' for plotting - plot() extends plotting area
# image(eRb, col = spec(1000), zlim= c(minValue(eRb),maxValue(eRb)), add=T)
# plot(landT, add =T, col = 'cornsilk3')
# plot(chem.spdfT, add=T, pch=19, col='black', cex=2.5)
# 
# axis(1, at=c( -890555.9, -667916.9, -445278.0), L, lwd.ticks=1, cex.axis=2, padj=0.8)
# abline(h=-1057535.2)
# axis(2, at=c(6800125, 6982998, 7170156, 7361866, 7558416, 7760119, 7967318, 8180387, 8399738), labels=LN, lwd.ticks=1, pos=-1057535.2, las=1,cex.axis=2)
# axis(4, at=c(6800125,8399738), labels=NA, lwd.ticks=0, pos=-278298.7)
# #axis(3, at=c(-1066000,-333000), labels=NA, lwd.ticks=0, pos=8404000)
# 
# #Legend
# plot(scale(eRb, center=F, scale=F), horizontal=F,  smallplot= c(0.6,0.62,0.2,0.8), col = spec(1000),legend.only=TRUE,  axis.args = list(cex.axis = 2))
# 


###Li


#par(mfrow=c(2,2))
# par(mar = c(5,6,4,2))
# image(pNa, col = 'white', xaxt='n', yaxt='n',xlim=c(-1057535.2,-278298.7), ylim= c(6800125,8399738), xlab=NA, ylab=NA) ###use image to keep plot in same 'window' for plotting - plot() extends plotting area
# image(pLi, col = spec(1000), zlim= c(minValue(pLi),maxValue(pLi)), add=T)
# plot(landT, add =T, col = 'cornsilk3')
# plot(chem.spdfT, add=T, pch=19, col='black', cex=2.5)
# 
# axis(1, at=c( -890555.9, -667916.9, -445278.0), L, lwd.ticks=1, cex.axis=2, padj=0.8)
# abline(h=-1057535.2)
# axis(2, at=c(6800125, 6982998, 7170156, 7361866, 7558416, 7760119, 7967318, 8180387, 8399738), labels=LN, lwd.ticks=1, pos=-1057535.2, las=1,cex.axis=2)
# axis(4, at=c(6800125,8399738), labels=NA, lwd.ticks=0, pos=-278298.7)
# #axis(3, at=c(-1066000,-333000), labels=NA, lwd.ticks=0, pos=8404000)
# 
# #Legend
# plot(pLi, horizontal=F,  smallplot= c(0.6,0.62,0.2,0.8), col = spec(1000),legend.only=TRUE,  axis.args = list(cex.axis = 2))
# 
# #Li- er
# #par(mfrow=c(2,2))
# par(mar = c(5,6,4,2))
# image(pNa, col = 'white', xaxt='n', yaxt='n',xlim=c(-1057535.2,-278298.7), ylim= c(6800125,8399738), xlab=NA, ylab=NA) ###use image to keep plot in same 'window' for plotting - plot() extends plotting area
# image(eLi, col = spec(1000), zlim= c(minValue(eLi),maxValue(eLi)), add=T)
# plot(landT, add =T, col = 'cornsilk3')
# plot(chem.spdfT, add=T, pch=19, col='black', cex=2.5)
# 
# axis(1, at=c( -890555.9, -667916.9, -445278.0), L, lwd.ticks=1, cex.axis=2, padj=0.8)
# abline(h=-1057535.2)
# axis(2, at=c(6800125, 6982998, 7170156, 7361866, 7558416, 7760119, 7967318, 8180387, 8399738), labels=LN, lwd.ticks=1, pos=-1057535.2, las=1,cex.axis=2)
# axis(4, at=c(6800125,8399738), labels=NA, lwd.ticks=0, pos=-278298.7)
# #axis(3, at=c(-1066000,-333000), labels=NA, lwd.ticks=0, pos=8404000)
# 
# #Legend
# plot(eLi, horizontal=F,  smallplot= c(0.6,0.62,0.2,0.8), col = spec(1000),legend.only=TRUE,  axis.args = list(cex.axis = 2))


###Sc


#par(mfrow=c(2,2))
# par(mar = c(5,6,4,2))
# image(pNa, col = 'white', xaxt='n', yaxt='n',xlim=c(-1057535.2,-278298.7), ylim= c(6800125,8399738), xlab=NA, ylab=NA) ###use image to keep plot in same 'window' for plotting - plot() extends plotting area
# image(pSc, col = spec(1000), zlim= c(minValue(pSc),maxValue(pSc)), add=T)
# plot(landT, add =T, col = 'cornsilk3')
# plot(chem.spdfT, add=T, pch=19, col='black', cex=2.5)
# 
# axis(1, at=c( -890555.9, -667916.9, -445278.0), L, lwd.ticks=1, cex.axis=2, padj=0.8)
# abline(h=-1057535.2)
# axis(2, at=c(6800125, 6982998, 7170156, 7361866, 7558416, 7760119, 7967318, 8180387, 8399738), labels=LN, lwd.ticks=1, pos=-1057535.2, las=1,cex.axis=2)
# axis(4, at=c(6800125,8399738), labels=NA, lwd.ticks=0, pos=-278298.7)
# #axis(3, at=c(-1066000,-333000), labels=NA, lwd.ticks=0, pos=8404000)
# 
# #Legend
# plot(scale(pSc), horizontal=F,  smallplot= c(0.6,0.62,0.2,0.8), col = spec(1000),legend.only=TRUE,  axis.args = list(cex.axis = 2))
# 
# #Sc- er
# #par(mfrow=c(2,2))
# par(mar = c(5,6,4,2))
# image(pNa, col = 'white', xaxt='n', yaxt='n',xlim=c(-1057535.2,-278298.7), ylim= c(6800125,8399738), xlab=NA, ylab=NA) ###use image to keep plot in same 'window' for plotting - plot() extends plotting area
# image(eSc, col = spec(1000), zlim= c(minValue(eSc),maxValue(eSc)), add=T)
# plot(landT, add =T, col = 'cornsilk3')
# plot(chem.spdfT, add=T, pch=19, col='black', cex=2.5)
# 
# axis(1, at=c( -890555.9, -667916.9, -445278.0), L, lwd.ticks=1, cex.axis=2, padj=0.8)
# abline(h=-1057535.2)
# axis(2, at=c(6800125, 6982998, 7170156, 7361866, 7558416, 7760119, 7967318, 8180387, 8399738), labels=LN, lwd.ticks=1, pos=-1057535.2, las=1,cex.axis=2)
# axis(4, at=c(6800125,8399738), labels=NA, lwd.ticks=0, pos=-278298.7)
# #axis(3, at=c(-1066000,-333000), labels=NA, lwd.ticks=0, pos=8404000)
# 
# #Legend
# plot(scale(eSc, center=T, scale=cellStats(pSc, 'sd')), horizontal=F,  smallplot= c(0.6,0.62,0.2,0.8), col = spec(1000),legend.only=TRUE,  axis.args = list(cex.axis = 2))


```